#ifndef _PIECE_MACROS_HPP_
#define _PIECE_MACROS_HPP_

#define BLACK_KNIGHT 1
#define BLACK_BISHOP 2
#define BLACK_PAWN 3
#define BLACK_LANCE 4
#define BLACK_SILVER 5
#define BLACK_ROOK 6
#define BLACK_GOLD 7
#define BLACK_KING 8
#define BLACK_PROMOTED_KNIGHT 9
#define BLACK_PROMOTED_BISHOP 10
#define BLACK_PROMOTED_PAWN 11
#define BLACK_PROMOTED_LANCE 12
#define BLACK_PROMOTED_SILVER 13
#define BLACK_PROMOTED_ROOK 14

#define WHITE_KNIGHT -1
#define WHITE_BISHOP -2
#define WHITE_PAWN -3
#define WHITE_LANCE -4
#define WHITE_SILVER -5
#define WHITE_ROOK -6
#define WHITE_GOLD -7
#define WHITE_KING -8
#define WHITE_PROMOTED_KNIGHT -9
#define WHITE_PROMOTED_BISHOP -10
#define WHITE_PROMOTED_PAWN -11
#define WHITE_PROMOTED_LANCE -12
#define WHITE_PROMOTED_SILVER -13
#define WHITE_PROMOTED_ROOK -14

#define DUMMY 17
#define EMPTY 0

#endif